export type CertJobStatus =
  | 'queued'
  | 'pending'
  | 'processing'
  | 'creating_account'
  | 'creating_order'
  | 'order_created'
  | 'waiting_order_ready'
  | 'order_ready'
  | 'cleanup_dns'
  | 'cleanup_warning'
  | 'presenting_dns'
  | 'waiting_propagation'
  | 'dns_propagated'
  | 'accepting_challenge'
  | 'waiting_order_valid'
  | 'order_valid'
  | 'validating'
  | 'validated'
  | 'finalizing'
  | 'finalized'
  | 'downloading'
  | 'downloaded'
  | 'issued'
  | 'failed'
  | 'waiting_ca'
  | 'disabled'

export const certJobStatusLabel = (status: CertJobStatus): string => {
  switch (status) {
    case 'issued': return '已签发'
    case 'failed': return '失败'
    case 'disabled': return '已禁用'
    case 'queued': return '排队中'
    case 'waiting_ca': return '等待 CA'
    case 'pending': return '待处理'
    case 'processing': return '处理中'
    case 'creating_account': return '创建账户'
    case 'creating_order': return '创建订单'
    case 'order_created': return '订单已创建'
    case 'waiting_order_ready': return '等待订单就绪'
    case 'order_ready': return '订单就绪'
    case 'cleanup_dns': return '清理 DNS'
    case 'cleanup_warning': return '清理警告'
    case 'presenting_dns': return '设置 DNS'
    case 'waiting_propagation': return '等待 DNS'
    case 'dns_propagated': return 'DNS 已传播'
    case 'accepting_challenge': return '提交验证'
    case 'waiting_order_valid': return '等待订单验证'
    case 'order_valid': return '订单验证完成'
    case 'validating': return '验证中'
    case 'validated': return '验证通过'
    case 'finalizing': return '最终化'
    case 'finalized': return '订单完成'
    case 'downloading': return '下载证书'
    case 'downloaded': return '下载完成'
  }
}
